services:
  metadata-db:
    image: postgres:15.3
    container_name: metadata_db
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./test_data.sql:/docker-entrypoint-initdb.d/test_data.sql
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=metadata_db
