services:
  metadata-db:
    image: postgres:16-alpine
    container_name: metadata_db
    ports:
      - 5432:5432
    volumes:
      - ~/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=metadata_db
